"""baseline schema

Revision ID: f4451315b779
Revises: 
Create Date: 2026-05-20 14:38:42.708222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4451315b779'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('google_sub', sa.String(length=64), nullable=True),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('youtube_description_template', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=True)
    op.create_table('beats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('bpm', sa.Integer(), nullable=True),
    sa.Column('music_key', sa.String(length=16), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('plays', sa.BigInteger(), nullable=False),
    sa.Column('platform_statuses', sa.JSON(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beats_user_id'), 'beats', ['user_id'], unique=False)
    op.create_table('platform_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('beatstars', 'youtube', 'soundcloud', 'spotify', 'audiomack', 'bandcamp', name='platformprovider'), nullable=False),
    sa.Column('status', sa.Enum('connected', 'disconnected', 'error', name='platformstatus'), nullable=False),
    sa.Column('account_label', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('session_data_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_connections_user_id'), 'platform_connections', ['user_id'], unique=False)
    op.create_table('upload_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('beat_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=True),
    sa.Column('tagged_storage_path', sa.String(length=1024), nullable=True),
    sa.Column('stems_storage_path', sa.String(length=1024), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'uploading', 'done', 'failed', name='uploadstatus'), nullable=False),
    sa.Column('license_type', sa.String(length=32), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.Column('artwork_storage_path', sa.String(length=1024), nullable=True),
    sa.Column('video_storage_path', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('targets', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_jobs_beat_id'), 'upload_jobs', ['beat_id'], unique=False)
    op.create_index(op.f('ix_upload_jobs_user_id'), 'upload_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_jobs_user_id'), table_name='upload_jobs')
    op.drop_index(op.f('ix_upload_jobs_beat_id'), table_name='upload_jobs')
    op.drop_table('upload_jobs')
    op.drop_index(op.f('ix_platform_connections_user_id'), table_name='platform_connections')
    op.drop_table('platform_connections')
    op.drop_index(op.f('ix_beats_user_id'), table_name='beats')
    op.drop_table('beats')
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
